# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Final\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1341, 894)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainTab = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTab.setObjectName("mainTab")
        self.tabID = QtWidgets.QWidget()
        self.tabID.setObjectName("tabID")
        self.gridLayout = QtWidgets.QGridLayout(self.tabID)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabID)
        self.groupBox_6.setObjectName("groupBox_6")
        self.btnSelect_IDCard = QtWidgets.QPushButton(self.groupBox_6)
        self.btnSelect_IDCard.setGeometry(QtCore.QRect(540, 420, 93, 28))
        self.btnSelect_IDCard.setObjectName("btnSelect_IDCard")
        self.btnOpen_IDCard = QtWidgets.QPushButton(self.groupBox_6)
        self.btnOpen_IDCard.setGeometry(QtCore.QRect(20, 30, 93, 28))
        self.btnOpen_IDCard.setObjectName("btnOpen_IDCard")
        self.treev_IDCard = QtWidgets.QTreeView(self.groupBox_6)
        self.treev_IDCard.setGeometry(QtCore.QRect(10, 420, 521, 281))
        self.treev_IDCard.setObjectName("treev_IDCard")
        self.grapvRaw_IDCard = QtWidgets.QGraphicsView(self.groupBox_6)
        self.grapvRaw_IDCard.setGeometry(QtCore.QRect(10, 70, 621, 341))
        self.grapvRaw_IDCard.setObjectName("grapvRaw_IDCard")
        self.gridLayout.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabID)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnExtract_IDCard = QtWidgets.QPushButton(self.groupBox_2)
        self.btnExtract_IDCard.setGeometry(QtCore.QRect(520, 300, 93, 28))
        self.btnExtract_IDCard.setObjectName("btnExtract_IDCard")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 450, 621, 261))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 141, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 141, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setGeometry(QtCore.QRect(10, 150, 141, 16))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(10, 190, 141, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(10, 230, 141, 16))
        self.label_14.setObjectName("label_14")
        self.txtbNumber_IDCard = QtWidgets.QTextEdit(self.groupBox_7)
        self.txtbNumber_IDCard.setGeometry(QtCore.QRect(160, 20, 451, 31))
        self.txtbNumber_IDCard.setObjectName("txtbNumber_IDCard")
        self.txtbName_IDCard = QtWidgets.QTextEdit(self.groupBox_7)
        self.txtbName_IDCard.setGeometry(QtCore.QRect(160, 60, 451, 31))
        self.txtbName_IDCard.setObjectName("txtbName_IDCard")
        self.txtbDOB_IDCard = QtWidgets.QTextEdit(self.groupBox_7)
        self.txtbDOB_IDCard.setGeometry(QtCore.QRect(160, 100, 451, 31))
        self.txtbDOB_IDCard.setObjectName("txtbDOB_IDCard")
        self.txtbSex_IDCard = QtWidgets.QTextEdit(self.groupBox_7)
        self.txtbSex_IDCard.setGeometry(QtCore.QRect(160, 140, 451, 31))
        self.txtbSex_IDCard.setObjectName("txtbSex_IDCard")
        self.txtbHomeTown_IDCard = QtWidgets.QTextEdit(self.groupBox_7)
        self.txtbHomeTown_IDCard.setGeometry(QtCore.QRect(160, 180, 451, 31))
        self.txtbHomeTown_IDCard.setObjectName("txtbHomeTown_IDCard")
        self.txtHome_IDCard = QtWidgets.QTextEdit(self.groupBox_7)
        self.txtHome_IDCard.setGeometry(QtCore.QRect(160, 220, 451, 31))
        self.txtHome_IDCard.setObjectName("txtHome_IDCard")
        self.grapv_IDCard = QtWidgets.QGraphicsView(self.groupBox_2)
        self.grapv_IDCard.setGeometry(QtCore.QRect(10, 20, 621, 271))
        self.grapv_IDCard.setObjectName("grapv_IDCard")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(30, 340, 61, 16))
        self.label_12.setObjectName("label_12")
        self.grapvFace_IDCard = QtWidgets.QGraphicsView(self.groupBox_2)
        self.grapvFace_IDCard.setGeometry(QtCore.QRect(170, 300, 141, 151))
        self.grapvFace_IDCard.setObjectName("grapvFace_IDCard")
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.mainTab.addTab(self.tabID, "")
        self.tabCI = QtWidgets.QWidget()
        self.tabCI.setObjectName("tabCI")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabCI)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabCI)
        self.groupBox_4.setObjectName("groupBox_4")
        self.btnSelect_CICard = QtWidgets.QPushButton(self.groupBox_4)
        self.btnSelect_CICard.setGeometry(QtCore.QRect(540, 420, 93, 28))
        self.btnSelect_CICard.setObjectName("btnSelect_CICard")
        self.btnOpen_CICard = QtWidgets.QPushButton(self.groupBox_4)
        self.btnOpen_CICard.setGeometry(QtCore.QRect(20, 30, 93, 28))
        self.btnOpen_CICard.setObjectName("btnOpen_CICard")
        self.treev_CICard = QtWidgets.QTreeView(self.groupBox_4)
        self.treev_CICard.setGeometry(QtCore.QRect(10, 420, 521, 341))
        self.treev_CICard.setObjectName("treev_CICard")
        self.grapvRaw_CICard = QtWidgets.QGraphicsView(self.groupBox_4)
        self.grapvRaw_CICard.setGeometry(QtCore.QRect(10, 70, 621, 341))
        self.grapvRaw_CICard.setObjectName("grapvRaw_CICard")
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.tabCI)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 460, 621, 301))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 141, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 141, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 141, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(10, 270, 141, 16))
        self.label_7.setObjectName("label_7")
        self.txtbNumber_CICard = QtWidgets.QTextEdit(self.groupBox_5)
        self.txtbNumber_CICard.setGeometry(QtCore.QRect(160, 20, 451, 31))
        self.txtbNumber_CICard.setObjectName("txtbNumber_CICard")
        self.txtbName_CICard = QtWidgets.QTextEdit(self.groupBox_5)
        self.txtbName_CICard.setGeometry(QtCore.QRect(160, 60, 451, 31))
        self.txtbName_CICard.setObjectName("txtbName_CICard")
        self.txtbDOB_CICard = QtWidgets.QTextEdit(self.groupBox_5)
        self.txtbDOB_CICard.setGeometry(QtCore.QRect(160, 100, 451, 31))
        self.txtbDOB_CICard.setObjectName("txtbDOB_CICard")
        self.txtbSex_CICard = QtWidgets.QTextEdit(self.groupBox_5)
        self.txtbSex_CICard.setGeometry(QtCore.QRect(160, 140, 451, 31))
        self.txtbSex_CICard.setObjectName("txtbSex_CICard")
        self.txtbNation_CICard = QtWidgets.QTextEdit(self.groupBox_5)
        self.txtbNation_CICard.setGeometry(QtCore.QRect(160, 180, 451, 31))
        self.txtbNation_CICard.setObjectName("txtbNation_CICard")
        self.txtbHomeTown_CICard = QtWidgets.QTextEdit(self.groupBox_5)
        self.txtbHomeTown_CICard.setGeometry(QtCore.QRect(160, 220, 451, 31))
        self.txtbHomeTown_CICard.setObjectName("txtbHomeTown_CICard")
        self.txtbHome__CICard = QtWidgets.QTextEdit(self.groupBox_5)
        self.txtbHome__CICard.setGeometry(QtCore.QRect(160, 260, 451, 31))
        self.txtbHome__CICard.setObjectName("txtbHome__CICard")
        self.btnExtract_CICard = QtWidgets.QPushButton(self.groupBox)
        self.btnExtract_CICard.setGeometry(QtCore.QRect(540, 310, 93, 28))
        self.btnExtract_CICard.setObjectName("btnExtract_CICard")
        self.grapv_CICard = QtWidgets.QGraphicsView(self.groupBox)
        self.grapv_CICard.setGeometry(QtCore.QRect(10, 20, 621, 281))
        self.grapv_CICard.setObjectName("grapv_CICard")
        self.grapvFace_CICard = QtWidgets.QGraphicsView(self.groupBox)
        self.grapvFace_CICard.setGeometry(QtCore.QRect(170, 310, 141, 151))
        self.grapvFace_CICard.setObjectName("grapvFace_CICard")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(20, 370, 61, 16))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.mainTab.addTab(self.tabCI, "")
        self.gridLayout_2.addWidget(self.mainTab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1341, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Extracted Data"))
        self.btnSelect_IDCard.setText(_translate("MainWindow", "Select Photos"))
        self.btnOpen_IDCard.setText(_translate("MainWindow", "Open Folder"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Extracted Data"))
        self.btnExtract_IDCard.setText(_translate("MainWindow", "Extract"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Content"))
        self.label_8.setText(_translate("MainWindow", "Số CMND:"))
        self.label_9.setText(_translate("MainWindow", "Họ và tên:"))
        self.label_10.setText(_translate("MainWindow", "Ngày, tháng, năm sinh:"))
        self.label_11.setText(_translate("MainWindow", "Giới tính:"))
        self.label_13.setText(_translate("MainWindow", "Nguyên quán:"))
        self.label_14.setText(_translate("MainWindow", "Nơi thường trú:"))
        self.label_12.setText(_translate("MainWindow", "Ảnh thẻ:"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tabID), _translate("MainWindow", "ID Card"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Load Photo"))
        self.btnSelect_CICard.setText(_translate("MainWindow", "Select Photos"))
        self.btnOpen_CICard.setText(_translate("MainWindow", "Open Folder"))
        self.groupBox.setTitle(_translate("MainWindow", "Extracted Data"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Content"))
        self.label.setText(_translate("MainWindow", "Số Thẻ căn cước:"))
        self.label_2.setText(_translate("MainWindow", "Họ và tên:"))
        self.label_3.setText(_translate("MainWindow", "Ngày, tháng, năm sinh:"))
        self.label_4.setText(_translate("MainWindow", "Giới tính:"))
        self.label_5.setText(_translate("MainWindow", "Quốc tịch"))
        self.label_6.setText(_translate("MainWindow", "Quê quán:"))
        self.label_7.setText(_translate("MainWindow", "Nơi thường trú:"))
        self.btnExtract_CICard.setText(_translate("MainWindow", "Extract"))
        self.label_15.setText(_translate("MainWindow", "Ảnh thẻ:"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tabCI), _translate("MainWindow", "CI Card"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "Open Folder"))
        self.actionOpen_Folder.setShortcut(_translate("MainWindow", "Ctrl+O"))
